#!/usr/bin/env bash

# Run this script to set up git hooks.

printErrorAndExit() {
  echo 'Failure during git development setup' 1>&2
  echo '------------------------------------' 1>&2
  echo '' 1>&2
  echo "$@" 1>&2
  exit 1
}

u=$(cd "$(echo "$0"|sed 's/[^/]*$//')"; pwd)
cd "$u/../.git/hooks"

# We need to have a git repository to do a pull.
if ! test -d ./.git; then
  git init || printErrorAndExit "Could not run git init."
fi &&

# Grab the hooks.
# Use the local hooks if possible.

# Set up uncrustify hook.
echo "Setting up the uncrustify hook..."
git config hooks.uncrustify.conf "Utilities/uncrustify.conf"

# Set up KWStyle hook.
echo "Setting up the KWStyle hook..."
git config hooks.KWStyle.conf "Utilities/KWStyle.xml.in"
git config hooks.KWStyle false

# Set up cppcheck hook.
echo "Setting up the cppcheck hook..."
git config hooks.cppcheck false

echo "Pulling the hooks..." &&
if GIT_DIR=.. git for-each-ref refs/remotes/origin/hooks 2>/dev/null | \
  grep -q '\<refs/remotes/origin/hooks$'; then
  url=https://github.com/jeanyves-yang/hooks.git/hooks
  branch=master
fi &&

git fetch -q "$url" "$branch" &&
git reset -q --hard FETCH_HEAD ||
    printErrorAndExit "Downloading the hooks failed."

cd ../..

echo "Done."
